### ISSUE TITLE
Make install issue with latest stable Ubuntu LTS 16.04

### ISSUE THREAD

**Issue by TheSandBoxMKG** [hadess/udraw#2]
```
root@valentin-HP-Laptop-15-bs0xx:/home/valentin/Documentos/udraw-sysdriver# make install
make -C /lib/modules/4.13.0-38-generic/build SUBDIRS=/home/valentin/Documentos/udraw-sysdriver modules_install
make[1]: se entra en el directorio '/usr/src/linux-headers-4.13.0-38-generic'
  INSTALL /home/valentin/Documentos/udraw-sysdriver/hid_udraw_ps3_standalone.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.13.0-38-generic
make[1]: se sale del directorio '/usr/src/linux-headers-4.13.0-38-generic'

```

So, this is stopping me from installing the driver since it seems to not find bss_file.c and certs/signing_key.pem

I wanted to ask if this is an issue with the driver.

**Comment by hadess** [comment]
I don't see any failures, just warnings about it not being able to sign the driver.

The driver is also already in that kernel version, why not ask your distributor to enable it instead of having to compile it yourself?

**Comment by TheSandBoxMKG** [comment]
Oh, I'm sorry, I didn't even notice at first that this was the driver that came out with the operating system. I'm sorry for bothering you, you can close this issue.

**Comment by hadess** [comment]
Well, it's where the driver that comes with the OS came from :)

I've added a note to the README file

**Comment by hadess** [comment]
Feel free to email me if you have problems with the driver, although it might be best to email the linux-input@ mailing-list and copy me, as other kernel developers can then also help.

(I'm guessing you didn't just compile the driver for fun, and had a problem with the existing one...)
